[package]
name = "Fibonacci_Number"
version = "0.1.0"
authors = ["Damon Marc Rocha <dmarcr1997@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
